<footer class="bs-docs-footer">
  <div class="container">
    <p>SISTEMA WEB PARA GERENCIAMENTO DE PROJETOS DE PESQUISA DO NIPETI</p>
    <p>NIPETI - NÚCLEO INTERDISCIPLINAR DE PESQUISA, ESTUDO E DESENVOLVIMENTO EM TECNOLOGIA DA INFORMAÇÃO</p>
  </div>
</footer>
